=== Chia-Network/chips/assets/chip-0007/schema.json
{
    "$id": "https://raw.githubusercontent.com/Chia-Network/chips/main/assets/chip-0007/schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "CHIP-0007",
    "description": "Chia NFT off-chain metadata format",
    "type": "object",
    "properties": {
        "format": {
            "type": "string",
            "enum": [
                "CHIP-0007"
            ],
            "description": "CHIP number of the metadata format"
        },
        "name": {
            "type": "string",
            "description": "Name of the NFT"
        },
        "description": {
            "type": "string",
            "description": "Description of the NFT"
        },
        "minting_tool": {
            "type": "string",
            "description": "Name or short tag of the minting tool used to create this NFT"
        },
        "sensitive_content": {
            "type": [
                "boolean",
                "array"
            ],
            "description": "Indicator for sensitive content within the NFT",
            "items": {
                "type": "string",
                "description": "List of types of sensitive content within the NFT"
            }
        },
        "series_number": {
            "type": "integer",
            "description": "Number that this NFT is within the series (sequence of distinct NFTs)",
            "minimum": 1
        },
        "series_total": {
            "type": "integer",
            "description": "Total number of NFTs within the series (sequence of distinct NFTs)",
            "minimum": 1
        },
        "attributes": {
            "type": "array",
            "description": "Attributes of the NFT that may be directly displayed to the user",
            "items": {
                "type": "object",
                "properties": {
                    "trait_type": {
                        "type": [
                            "integer",
                            "string"
                        ],
                        "description": "Name of the NFT attribute"
                    },
                    "value": {
                        "type": [
                            "integer",
                            "string"
                        ],
                        "description": "Value of the NFT attribute"
                    },
                    "min_value": {
                        "type": "integer",
                        "description": "Minimum value of the NFT attribute in relation to other NFTs. Only applicable to integers."
                    },
                    "max_value": {
                        "type": "integer",
                        "description": "Maximum value of the NFT attribute in relation to other NFTs. Only applicable to integers."
                    }
                },
                "required": [
                    "trait_type",
                    "value"
                ]
            }
        },
        "collection": {
            "type": "object",
            "description": "NFT collection information",
            "properties": {
                "name": {
                    "type": "string",
                     "description": "Name of the NFT collection"
                },
                "id": {
                    "type": "string",
                    "format": "uuid",
                     "description": "ID of the NFT collection"
                },
                "attributes": {
                    "type": "array",
                    "description": "Attributes of the NFT collection",
                    "items": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "type": [
                                    "integer",
                                    "string"
                                ],
                                "description": "Name of the NFT collection attribute"
                            },
                            "value": {
                                "type": [
                                    "integer",
                                    "string"
                                ],
                                "description": "Value of the NFT collection attribute"
                            }
                        },
                        "required": [
                            "type",
                            "value"
                        ]
                    }
                }
            },
            "required": [
                "name",
                "id"
            ]
        },
        "data": {
            "type": "object",
            "description": "Any NFT data which is not suitable for the attributes array, such as non-human-readable data"
        }
    },
    "required": [
        "format",
        "name",
        "description"
    ]
}

=== Chia-Network/chips/assets/chip-0007/example.json
{
    "format": "CHIP-0007",
    "name": "Pikachu",
    "description": "Electric-type Pokémon with stretchy cheeks",
    "minting_tool": "SuperMinter/2.5.2",
    "sensitive_content": false,
    "series_number": 22,
    "series_total": 1000,
    "attributes": [
        {
            "trait_type": "Species",
            "value": "Mouse"
        },
        {
            "trait_type": "Color",
            "value": "Yellow"
        },
        {
            "trait_type": "Friendship",
            "value": 50,
            "min_value": 0,
            "max_value": 255
        }
    ],
    "collection": {
        "name": "Example Pokémon Collection",
        "id": "e43fcfe6-1d5c-4d6e-82da-5de3aa8b3b57",
        "attributes": [
            {
                "type": "description",
                "value": "Example Pokémon Collection is the best Pokémon collection. Get yours today!"
            },
            {
                "type": "icon",
                "value": "https://examplepokemoncollection.com/image/icon.png"
            },
            {
                "type": "banner",
                "value": "https://examplepokemoncollection.com/image/banner.png"
            },
            {
                "type": "twitter",
                "value": "ExamplePokemonCollection"
            },
            {
                "type": "website",
                "value": "https://examplepokemoncollection.com/"
            }
        ]
    },
    "data": {
        "example_data": "VGhpcyBpcyBhbiBleGFtcGxlIG9mIGRhdGEgdGhhdCB5b3UgbWlnaHQgd2FudCB0byBzdG9yZSBpbiB0aGUgZGF0YSBvYmplY3QuIE5GVCBhdHRyaWJ1dGVzIHdoaWNoIGFyZSBub3QgaHVtYW4gcmVhZGFibGUgc2hvdWxkIGJlIHBsYWNlZCB3aXRoaW4gdGhpcyBvYmplY3QsIGFuZCB0aGUgYXR0cmlidXRlcyBhcnJheSB1c2VkIG9ubHkgZm9yIGluZm9ybWF0aW9uIHdoaWNoIGlzIGludGVuZGVkIHRvIGJlIHJlYWQgYnkgdGhlIHVzZXIu"
    }
}
